#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Atticus Bold

# Short bio or description (displayed in the header)
description: The Words of Atticus Bold

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar:

theme: jekyll-theme-cayman
