#
# This file contains configuration flags to customize this site
#

# Name of the site (displayed in the header)
name: Atticus Bold

# Short bio or description (displayed in the header)
description: The Words of Atticus Bold

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar:

permalink: /journal/blog/:year/:month/:day/:title

# Enable Pagination
paginate: 5
paginate_path: "/journal/blog/page:num/"

theme: jekyll-theme-midnight
